/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorials: [
    {
      type: "category",
      label: "Start Here",
      items: [{ type: "autogenerated", dirName: "start_here" }],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [{ type: "autogenerated", dirName: "tutorials" }],
    },
  ],
  api: [
    {
      type: "category",
      label: "Globals",
      items: [{ type: "autogenerated", dirName: "globals" }],
    },
    {
      type: "category",
      label: "Enums",
      items: [{ type: "autogenerated", dirName: "enums" }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
