name: Build Pull Request

on:
  pull_request:
    branches: ["main"]
    types: [opened, reopened, synchronize]

concurrency: preview-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Write Pull Request Details
        run: |
          echo ${{ github.event.number }} > ./build/.pr_number &&
          echo ${{ github.event.pull_request.head.sha }} > ./build/.pr_commit_hash

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build/
          retention-days: 1
