# Clones the repository which then begins with building the environment,
# Once built, It deploys the built wiki.

name: Deploy Wiki

on:
    push:
        branches: [ "main" ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v6

            - name: Setup and Build
              uses: ./.github/actions/setup-env
              with:
                  build: true

            - name: Deploy built wiki
              uses: cloudflare/wrangler-action@v3
              with:
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  command: pages deploy ./build --project-name=figura-wiki
                  gitHubToken: ${{ secrets.GH_BOT_TOKEN }}
