name: Build Pull Request

on:
  pull_request:
    branches: ["main"]
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-env
        with:
          build: true

      - name: Write Pull Request Details
        run: |
          echo ${{ github.event.number }} > ./build/.pr_number &&
          echo ${{ github.event.pull_request.head.sha }} > ./build/.pr_commit_hash

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build/
          retention-days: 1
